# Generated by Django 3.1.4 on 2021-10-24 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_patient_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.userprofile'),
        ),
    ]
