# Generated by Django 3.1.4 on 2021-10-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_auto_20211027_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_status',
            field=models.CharField(choices=[('Incomplete', 'Incomplete'), ('Complete', 'Complete')], max_length=100),
        ),
    ]
